/**
 * Wires the release signing config into the generated Android project.
 *
 * `android/` is regenerated by prebuild, so a signing block edited in by hand
 * disappears on the next run and the build quietly falls back to the debug
 * key — which Play rejects. This plugin puts it back every time.
 *
 * The keystore path and passwords come from the environment, so nothing
 * secret is written into a file that could be committed. When they are
 * absent the project is left alone and release builds stay debug-signed,
 * which is what a contributor without the key should get.
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

const RELEASE_CONFIG = `
        release {
            storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }`;

module.exports = function withUploadSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (!process.env.ANDROID_KEYSTORE_PATH) return cfg;

    let gradle = cfg.modResults.contents;

    if (!gradle.includes('ANDROID_KEYSTORE_PATH')) {
      gradle = gradle.replace(/signingConfigs \{/, `signingConfigs {${RELEASE_CONFIG}`);
    }

    /*
     * Only the release variant is retargeted, and only inside buildTypes.
     * Searching the whole file matches the debug variant first — and before
     * that the "release" entry inside signingConfigs itself — which left the
     * release build debug-signed while appearing to have worked.
     */
    const at = gradle.indexOf('buildTypes {');
    if (at !== -1) {
      const tail = gradle
        .slice(at)
        .replace(
          /(release \{[^}]*?)signingConfig signingConfigs\.debug/,
          '$1signingConfig signingConfigs.release',
        );
      gradle = gradle.slice(0, at) + tail;
    }

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
